Here are some useful resources that will help you get the most out of Pagetest:
<br>
<ul>
<li><a href="http://www.artzstudio.com/2008/07/optimizing-web-performance-with-aol-pagetest/">Video tutorial by David Artz on using Pagetest</a></li>
<li><a href="http://www.ryandoherty.net/2008/10/12/optimizing-openspacebook/">Walkthrough by Ryan Doherty examining the impact of optimization on performance</a></li>
<li><a href="http://www.aptimize.net/Blog/">Aptimize blog - interesting tools for automating optimization and the host of the New Zealand test location</a></li>
<li><a href="http://daemonsolutions.co.uk/">Daemon Solutions - The host of the UK test location</a></li>
<li><a href="http://www.strangeloopnetworks.com/">Strangeloop Networks - The host of the San Jose test location</a></li>
<li><a href="http://blog.patrickmeenan.com/">My Blog</a></li>
</ul>
<div style="background:yellow; padding:1em;">
<b>Thanks to <a href="http://www.strangeloopnetworks.com/">Strangeloop Networks</a>, testing from the west coast (San Jose) is now available.</b>
</div>