Welcome. Pagetest allows you to provide the URL of a webpage to be tested.
The test will be conducted from the location specified and you will be provided a waterfall of your page load performance 
as well as a comparison against an optimization checklist. Please 
visit the <a href="http://pagetest.wiki.sourceforge.net/">PageTest wiki page</a> for more information. Sample results 
for AOL.com can be seen <a href="/result/sample/">here</a>.
<br><br>
This tool lets you test web pages that are directly accessible as an URL from the Internet.  If you need to test a page inside of a 
firewall or something more complicated than a web page (an authenticated product like webmail for example) please download the
<a href="http://pagetest.sourceforge.net">desktop version of PageTest</a> which this is based on.
