<?php if( strncmp($_SERVER['REMOTE_ADDR'], "64.236.",  7)) { ?>
<div style="width:100%; height:90; text-align:center;">
    <script type="text/javascript"><!--
    google_ad_client = "pub-0388499782819905";
    /* Webpagetest Optimization Middle 728x90 */
    google_ad_slot = "0090008850";
    google_ad_width = 728;
    google_ad_height = 90;
    //-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
</div>
<?php } ?>
