<?php if( strncmp($_SERVER['REMOTE_ADDR'], "64.236.",  7)) { ?>
<div style="float:right; width:728; height:90; margin:0.5em;">
    <a target="_blank" href="http://www.aptimize.com/benefits?utm_source=webpagetestlogopatrick&utm_medium=aptimizelogo&utm_campaign=webpagetestlogopatrick">
    <img border="0" alt="Speed up your SharePoint or ASP.NET site instantly. No extra hardware, no code changes." src="/custom/NZ/aptimize_728_90.gif"/>
    </a>
</div>
<?php } ?>
